[workspace]
authors = ["Ricardo Garcia Silva <ricardo.garcia.silva@gmail.com>"]
channels = ["conda-forge"]
name = "demo2"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
prefect = ">=3.4.11,<4"
whenever = ">=0.8.8,<0.9"
cowpy = ">=1.1.5,<2"
